name: QA Sampling Automation

on:
  schedule:
    # Run at 7am Vietnam time (UTC+7) which is midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-sampling-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth google-auth-oauthlib google-auth-httplib2 pandas matplotlib
          
      - name: Create token file
        run: echo '${{ secrets.GOOGLE_TOKEN_JSON }}' > token.json
        
      - name: Run QA sampling automation script
        env:
          CI: true
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python Nem.py
        
      # Removing the upload-artifact action that's causing issues
      # If you need to capture logs, consider using a different approach
      # such as printing them to the console output
