name: QA Sampling Schedule Update

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1:00 AM UTC daily
  workflow_dispatch:     # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth pandas matplotlib
          
      - name: Run QA Sampling Update
        env:
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python qa_sampling_manager.py
